# frozen_string_literal: true

customize_gemfiles do
  {
    single_quotes: true,
    heading: "frozen_string_literal: true

This file was generated by Appraisal"
  }
end

appraise 'rails-6-0' do
  gem 'rails', '~> 6.0.0'
end

appraise 'rails-6-1' do
  gem 'rails', '~> 6.1'
end

appraise 'rails-7-0' do
  gem 'rails', '~> 7.0.0'
end

appraise 'rails-edge' do
  gem 'rails', github: 'rails/rails'
end

appraise 'rack-edge' do
  gem 'rack', github: 'rack/rack'
end

appraise 'multi_json' do
  gem 'multi_json', require: 'multi_json'
end

appraise 'multi_xml' do
  gem 'multi_xml', require: 'multi_xml'
end

appraise 'rack_1_0' do
  gem 'rack', '~> 1.0'
end

appraise 'rack_2_0' do
  gem 'rack', '~> 2.0'
end

appraise 'rack_3_0' do
  gem 'rack', '~> 3.0.0'
end

appraise 'no_dry_validation' do
  group :development, :test do
    remove_gem 'dry-validation'
  end
end
