---
name: danger
on: pull_request

jobs:
  danger:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 0
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.4
        bundler-cache: true
    - name: Run Danger
      env:
        BASE_SHA: ${{ github.event.pull_request.base.sha }}
        HEAD_SHA: ${{ github.event.pull_request.head.sha }}
        PR_NUMBER: ${{ github.event.pull_request.number }}
        DANGER_REPORT_PATH: danger_report.json
      run: bundle exec danger dry_run --base=$BASE_SHA --head=$HEAD_SHA --verbose
    - name: Upload Danger report
      uses: actions/upload-artifact@v5
      with:
        name: danger-report
        path: danger_report.json
